package com.mico.project.controller;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.file.Paths;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;

import com.mico.project.domain.User;
import com.mico.project.repository.UserRepository;

@Controller 
@RequestMapping("/hello") 
public class HelloController { 

	private static String UPLOADED_FOLDER = "D://temp//";
	
	@RequestMapping(value="", method=RequestMethod.GET) 
	public String hello() { return "/hello"; } 

	
	@RequestMapping("/greeting") 
	public String greeting() { return "index"; }

	
	@RequestMapping(value = "/ajaxUpload")
    public String ajaxUpload() {
        return "ajaxUpload";
    }

    @RequestMapping(value = "/fileUpload", method = RequestMethod.POST)
    @ResponseBody
    public ResponseEntity<?> uploadFile(
        @RequestParam("uploadfile") MultipartFile uploadfile) {
      
      try {
        // Get the filename and build the local file path
        String filename = uploadfile.getOriginalFilename();
        String directory = UPLOADED_FOLDER;
        String filepath = Paths.get(directory, filename).toString();
        
        // Save the file locally
        BufferedOutputStream stream =
            new BufferedOutputStream(new FileOutputStream(new File(filepath)));
        stream.write(uploadfile.getBytes());
        stream.close();
      }
      catch (Exception e) {
        System.out.println(e.getMessage());
        return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
      }
      
      return new ResponseEntity<>(HttpStatus.OK);
    } // method uploadFile


    
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
//	@GetMapping(path="/add") // Map ONLY GET Requests
//	public @ResponseBody String addNewUser (@RequestParam String name
//		, @RequestParam String email) {
//		// @ResponseBody means the returned String is the response, not a view name
//		// @RequestParam means it is a parameter from the GET or POST request
//	
//		User n = new User();
//		n.setUserame(name);
//		n.setEmail(email);
//		userRepository.save(n);
//		return "Saved";
//	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

} 

	


